-- Fix NotificationDispatchAttempts table by adding missing columns
-- This script handles the case where indexes might not exist

-- First, let's check if the NotificationDispatchAttempts table exists
DO $$
BEGIN
    -- Check if the table exists
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'NotificationDispatchAttempts') THEN
        -- Create the table if it doesn't exist
        CREATE TABLE "NotificationDispatchAttempts" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY,
            "NotificationId" uuid NOT NULL,
            "Channel" integer NOT NULL,
            "Status" integer NOT NULL,
            "AttemptedAt" timestamp with time zone NOT NULL,
            "CompletedAt" timestamp with time zone,
            "DeliveredAt" timestamp with time zone,
            "ErrorMessage" character varying(2000),
            "ErrorDetails" character varying(4000),
            "ExternalReference" character varying(500),
            "ExternalId" character varying(500),
            "RetryCount" integer NOT NULL DEFAULT 0,
            "AttemptNumber" integer NOT NULL DEFAULT 1,
            "NextRetryAt" timestamp with time zone,
            "NotificationTemplateId" integer,
            CONSTRAINT "PK_NotificationDispatchAttempts" PRIMARY KEY ("Id")
        );
        
        -- Create indexes
        CREATE INDEX "IX_NotificationDispatchAttempts_NotificationId" ON "NotificationDispatchAttempts" ("NotificationId");
        CREATE INDEX "IX_NotificationDispatchAttempts_Status" ON "NotificationDispatchAttempts" ("Status");
        CREATE INDEX "IX_NotificationDispatchAttempts_Channel" ON "NotificationDispatchAttempts" ("Channel");
        CREATE INDEX "IX_NotificationDispatchAttempts_AttemptedAt" ON "NotificationDispatchAttempts" ("AttemptedAt");
        CREATE INDEX "IX_NotificationDispatchAttempts_DeliveredAt" ON "NotificationDispatchAttempts" ("DeliveredAt");
        CREATE INDEX "IX_NotificationDispatchAttempts_AttemptNumber" ON "NotificationDispatchAttempts" ("AttemptNumber");
        CREATE INDEX "IX_NotificationDispatchAttempts_NotificationTemplateId" ON "NotificationDispatchAttempts" ("NotificationTemplateId");
        CREATE INDEX "IX_NotificationDispatchAttempts_Status_NextRetryAt" ON "NotificationDispatchAttempts" ("Status", "NextRetryAt");
        
        RAISE NOTICE 'NotificationDispatchAttempts table created successfully';
    ELSE
        -- Table exists, check and add missing columns
        
        -- Add DeliveredAt column if it doesn't exist
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'NotificationDispatchAttempts' AND column_name = 'DeliveredAt') THEN
            ALTER TABLE "NotificationDispatchAttempts" ADD COLUMN "DeliveredAt" timestamp with time zone;
            RAISE NOTICE 'Added DeliveredAt column';
        END IF;
        
        -- Add ErrorDetails column if it doesn't exist
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'NotificationDispatchAttempts' AND column_name = 'ErrorDetails') THEN
            ALTER TABLE "NotificationDispatchAttempts" ADD COLUMN "ErrorDetails" character varying(4000);
            RAISE NOTICE 'Added ErrorDetails column';
        END IF;
        
        -- Add ExternalId column if it doesn't exist
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'NotificationDispatchAttempts' AND column_name = 'ExternalId') THEN
            ALTER TABLE "NotificationDispatchAttempts" ADD COLUMN "ExternalId" character varying(500);
            RAISE NOTICE 'Added ExternalId column';
        END IF;
        
        -- Add AttemptNumber column if it doesn't exist
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'NotificationDispatchAttempts' AND column_name = 'AttemptNumber') THEN
            ALTER TABLE "NotificationDispatchAttempts" ADD COLUMN "AttemptNumber" integer NOT NULL DEFAULT 1;
            RAISE NOTICE 'Added AttemptNumber column';
        END IF;
        
        -- Add NotificationTemplateId column if it doesn't exist
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'NotificationDispatchAttempts' AND column_name = 'NotificationTemplateId') THEN
            ALTER TABLE "NotificationDispatchAttempts" ADD COLUMN "NotificationTemplateId" integer;
            RAISE NOTICE 'Added NotificationTemplateId column';
        END IF;
        
        -- Update existing records to have AttemptNumber = 1 if it's NULL or 0
        UPDATE "NotificationDispatchAttempts" 
        SET "AttemptNumber" = 1 
        WHERE "AttemptNumber" IS NULL OR "AttemptNumber" = 0;
        
        -- Create indexes if they don't exist
        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_NotificationDispatchAttempts_DeliveredAt') THEN
            CREATE INDEX "IX_NotificationDispatchAttempts_DeliveredAt" ON "NotificationDispatchAttempts" ("DeliveredAt");
            RAISE NOTICE 'Created DeliveredAt index';
        END IF;
        
        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_NotificationDispatchAttempts_AttemptNumber') THEN
            CREATE INDEX "IX_NotificationDispatchAttempts_AttemptNumber" ON "NotificationDispatchAttempts" ("AttemptNumber");
            RAISE NOTICE 'Created AttemptNumber index';
        END IF;
        
        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_NotificationDispatchAttempts_NotificationTemplateId') THEN
            CREATE INDEX "IX_NotificationDispatchAttempts_NotificationTemplateId" ON "NotificationDispatchAttempts" ("NotificationTemplateId");
            RAISE NOTICE 'Created NotificationTemplateId index';
        END IF;
        
        RAISE NOTICE 'NotificationDispatchAttempts table updated successfully';
    END IF;
    
    -- Check if NotificationTemplates table exists before creating foreign key
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'NotificationTemplates') THEN
        -- Check if foreign key constraint already exists
        IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints 
                      WHERE constraint_name = 'FK_NotificationDispatchAttempts_NotificationTemplates_NotificationTemplateId') THEN
            -- Add foreign key constraint
            ALTER TABLE "NotificationDispatchAttempts" 
            ADD CONSTRAINT "FK_NotificationDispatchAttempts_NotificationTemplates_NotificationTemplateId"
            FOREIGN KEY ("NotificationTemplateId") 
            REFERENCES "NotificationTemplates"("Id")
            ON DELETE SET NULL;
            RAISE NOTICE 'Added foreign key constraint to NotificationTemplates';
        END IF;
    END IF;
    
    -- Check if Notifications table exists before creating foreign key
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'Notifications') THEN
        -- Check if foreign key constraint already exists
        IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints 
                      WHERE constraint_name = 'FK_NotificationDispatchAttempts_Notifications_NotificationId') THEN
            -- Add foreign key constraint
            ALTER TABLE "NotificationDispatchAttempts" 
            ADD CONSTRAINT "FK_NotificationDispatchAttempts_Notifications_NotificationId"
            FOREIGN KEY ("NotificationId") 
            REFERENCES "Notifications"("NotificationId")
            ON DELETE CASCADE;
            RAISE NOTICE 'Added foreign key constraint to Notifications';
        END IF;
    END IF;
    
END $$;

-- Verify the table structure
SELECT 'NotificationDispatchAttempts table schema fix completed successfully' as status;