using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRM.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddMissingNotificationDispatchColumns : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Guard AddColumn for Notifications existing deployments
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'Notifications' AND column_name = 'Id'
                    ) THEN
                        ALTER TABLE ""Notifications"" ADD COLUMN ""Id"" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'Notifications' AND column_name = 'Metadata'
                    ) THEN
                        ALTER TABLE ""Notifications"" ADD COLUMN ""Metadata"" text NULL;
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'Notifications' AND column_name = 'Priority'
                    ) THEN
                        ALTER TABLE ""Notifications"" ADD COLUMN ""Priority"" integer NOT NULL DEFAULT 0;
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""NotificationAlerts"" (
                    ""Id"" uuid PRIMARY KEY,
                    ""AlertType"" text NOT NULL,
                    ""Severity"" text NOT NULL,
                    ""Message"" text NOT NULL,
                    ""Metadata"" text NULL,
                    ""Timestamp"" timestamp with time zone NOT NULL,
                    ""IsResolved"" boolean NOT NULL,
                    ""ResolvedAt"" timestamp with time zone NULL,
                    ""ResolvedBy"" text NULL,
                    ""ResolutionNotes"" text NULL
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""NotificationChannelConfigurations"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Channel"" integer NOT NULL,
                    ""IsEnabled"" boolean NOT NULL DEFAULT TRUE,
                    ""Configuration"" jsonb NOT NULL,
                    ""MaxRetryAttempts"" integer NOT NULL DEFAULT 3,
                    ""RetryDelay"" interval NOT NULL DEFAULT interval '00:05:00',
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NOT NULL
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""NotificationOperationLogs"" (
                    ""Id"" uuid PRIMARY KEY,
                    ""OperationType"" text NOT NULL,
                    ""Channel"" text NOT NULL,
                    ""Status"" text NOT NULL,
                    ""NotificationId"" uuid NULL,
                    ""UserId"" uuid NULL,
                    ""AttemptNumber"" integer NOT NULL,
                    ""Duration"" interval NULL,
                    ""ErrorMessage"" text NULL,
                    ""Metadata"" text NULL,
                    ""Timestamp"" timestamp with time zone NOT NULL
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""NotificationTemplates"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""TemplateKey"" character varying(100) NOT NULL,
                    ""Name"" text NOT NULL,
                    ""Description"" text NULL,
                    ""EventType"" character varying(100) NOT NULL,
                    ""Channel"" integer NOT NULL,
                    ""Subject"" character varying(500) NULL,
                    ""BodyTemplate"" character varying(4000) NOT NULL,
                    ""IsActive"" boolean NOT NULL DEFAULT TRUE,
                    ""RequiredVariables"" text NULL,
                    ""Variables"" text NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NOT NULL
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""NotificationDispatchAttempts"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""NotificationId"" uuid NOT NULL,
                    ""Channel"" integer NOT NULL,
                    ""Status"" integer NOT NULL,
                    ""AttemptedAt"" timestamp with time zone NOT NULL,
                    ""CompletedAt"" timestamp with time zone NULL,
                    ""DeliveredAt"" timestamp with time zone NULL,
                    ""ErrorMessage"" character varying(2000) NULL,
                    ""ErrorDetails"" character varying(4000) NULL,
                    ""ExternalReference"" character varying(500) NULL,
                    ""ExternalId"" character varying(500) NULL,
                    ""RetryCount"" integer NOT NULL DEFAULT 0,
                    ""AttemptNumber"" integer NOT NULL DEFAULT 1,
                    ""NextRetryAt"" timestamp with time zone NULL,
                    ""NotificationTemplateId"" integer NULL,
                    ""NotificationTemplateId1"" integer NULL
                );
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'IX_NotificationChannelConfigurations_Channel'
                    ) THEN
                        CREATE UNIQUE INDEX ""IX_NotificationChannelConfigurations_Channel"" ON ""NotificationChannelConfigurations""(""Channel"");
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'IX_NotificationChannelConfigurations_IsEnabled'
                    ) THEN
                        CREATE INDEX ""IX_NotificationChannelConfigurations_IsEnabled"" ON ""NotificationChannelConfigurations""(""IsEnabled"");
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'IX_NotificationDispatchAttempts_AttemptedAt'
                    ) THEN
                        CREATE INDEX ""IX_NotificationDispatchAttempts_AttemptedAt"" ON ""NotificationDispatchAttempts""(""AttemptedAt"");
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'IX_NotificationDispatchAttempts_AttemptNumber'
                    ) THEN
                        CREATE INDEX ""IX_NotificationDispatchAttempts_AttemptNumber"" ON ""NotificationDispatchAttempts""(""AttemptNumber"");
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'IX_NotificationDispatchAttempts_Channel'
                    ) THEN
                        CREATE INDEX ""IX_NotificationDispatchAttempts_Channel"" ON ""NotificationDispatchAttempts""(""Channel"");
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'IX_NotificationDispatchAttempts_DeliveredAt'
                    ) THEN
                        CREATE INDEX ""IX_NotificationDispatchAttempts_DeliveredAt"" ON ""NotificationDispatchAttempts""(""DeliveredAt"");
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'IX_NotificationDispatchAttempts_NotificationId'
                    ) THEN
                        CREATE INDEX ""IX_NotificationDispatchAttempts_NotificationId"" ON ""NotificationDispatchAttempts""(""NotificationId"");
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'IX_NotificationDispatchAttempts_NotificationTemplateId'
                    ) THEN
                        CREATE INDEX ""IX_NotificationDispatchAttempts_NotificationTemplateId"" ON ""NotificationDispatchAttempts""(""NotificationTemplateId"");
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'NotificationDispatchAttempts' AND column_name = 'NotificationTemplateId1'
                    ) THEN
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'IX_NotificationDispatchAttempts_NotificationTemplateId1'
                        ) THEN
                            CREATE INDEX ""IX_NotificationDispatchAttempts_NotificationTemplateId1"" ON ""NotificationDispatchAttempts""(""NotificationTemplateId1"");
                        END IF;
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'IX_NotificationDispatchAttempts_Status'
                    ) THEN
                        CREATE INDEX ""IX_NotificationDispatchAttempts_Status"" ON ""NotificationDispatchAttempts""(""Status"");
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'IX_NotificationDispatchAttempts_Status_NextRetryAt'
                    ) THEN
                        CREATE INDEX ""IX_NotificationDispatchAttempts_Status_NextRetryAt"" ON ""NotificationDispatchAttempts""(""Status"", ""NextRetryAt"");
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'NotificationTemplates' AND column_name = 'EventType'
                    ) THEN
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'IX_NotificationTemplates_EventType'
                        ) THEN
                            CREATE INDEX ""IX_NotificationTemplates_EventType"" ON ""NotificationTemplates""(""EventType"");
                        END IF;
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'NotificationTemplates' AND column_name = 'IsActive'
                    ) THEN
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'IX_NotificationTemplates_IsActive'
                        ) THEN
                            CREATE INDEX ""IX_NotificationTemplates_IsActive"" ON ""NotificationTemplates""(""IsActive"");
                        END IF;
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'NotificationTemplates' AND column_name = 'TemplateKey'
                    ) AND EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'NotificationTemplates' AND column_name = 'Channel'
                    ) THEN
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'IX_NotificationTemplates_TemplateKey_Channel'
                        ) THEN
                            CREATE UNIQUE INDEX ""IX_NotificationTemplates_TemplateKey_Channel"" ON ""NotificationTemplates""(""TemplateKey"", ""Channel"");
                        END IF;
                    END IF;
                END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "NotificationAlerts");

            migrationBuilder.DropTable(
                name: "NotificationChannelConfigurations");

            migrationBuilder.DropTable(
                name: "NotificationDispatchAttempts");

            migrationBuilder.DropTable(
                name: "NotificationOperationLogs");

            migrationBuilder.DropTable(
                name: "NotificationTemplates");

            migrationBuilder.DropColumn(
                name: "Id",
                table: "Notifications");

            migrationBuilder.DropColumn(
                name: "Metadata",
                table: "Notifications");

            migrationBuilder.DropColumn(
                name: "Priority",
                table: "Notifications");
        }
    }
}
