// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using CRM.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRM.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CRM.Domain.Entities.Adjustment", b =>
                {
                    b.Property<Guid>("AdjustmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AdjustedAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("AdjustmentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("AppliedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ApprovalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovalLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("OriginalAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("RequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("AdjustmentId");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("QuotationId")
                        .HasDatabaseName("IX_Adjustments_QuotationId");

                    b.HasIndex("RequestDate")
                        .HasDatabaseName("IX_Adjustments_RequestDate");

                    b.HasIndex("RequestedByUserId")
                        .HasDatabaseName("IX_Adjustments_RequestedByUserId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Adjustments_Status");

                    b.ToTable("Adjustments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Adjustments_Amount", "\"AdjustedAmount\" > 0");

                            t.HasCheckConstraint("CK_Adjustments_Status", "\"Status\" IN ('PENDING', 'APPROVED', 'REJECTED', 'APPLIED')");

                            t.HasCheckConstraint("CK_Adjustments_Type", "\"AdjustmentType\" IN ('DISCOUNT_CHANGE', 'AMOUNT_CORRECTION', 'TAX_CORRECTION')");
                        });
                });

            modelBuilder.Entity("CRM.Domain.Entities.AnalyticsMetricsSnapshot", b =>
                {
                    b.Property<Guid>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<JsonDocument>("MetricData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("PeriodDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SnapshotId");

                    b.HasIndex("CalculatedAt")
                        .HasDatabaseName("IX_AnalyticsMetricsSnapshot_CalculatedAt");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AnalyticsMetricsSnapshot_UserId");

                    b.HasIndex("MetricType", "PeriodDate")
                        .HasDatabaseName("IX_AnalyticsMetricsSnapshot_MetricType_PeriodDate");

                    b.ToTable("AnalyticsMetricsSnapshot", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Gstin")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PhoneCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("PinCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StateCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClientId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("Gstin");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("CreatedByUserId", "DeletedAt");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.ClientHistory", b =>
                {
                    b.Property<Guid>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AfterSnapshot")
                        .HasColumnType("jsonb");

                    b.Property<string>("BeforeSnapshot")
                        .HasColumnType("jsonb");

                    b.Property<List<string>>("ChangedFields")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<short>("SuspicionScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.HasKey("HistoryId");

                    b.HasIndex("ActorUserId", "CreatedAt")
                        .HasDatabaseName("IX_ClientHistories_Actor_CreatedAt");

                    b.HasIndex("ClientId", "CreatedAt")
                        .HasDatabaseName("IX_ClientHistories_ClientId_CreatedAt");

                    b.ToTable("ClientHistories", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.DashboardBookmark", b =>
                {
                    b.Property<Guid>("BookmarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<JsonDocument>("DashboardConfig")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("DashboardName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("BookmarkId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_DashboardBookmarks_UserId");

                    b.HasIndex("UserId", "IsDefault")
                        .IsUnique()
                        .HasDatabaseName("IX_DashboardBookmarks_UserId_IsDefault")
                        .HasFilter("\"IsDefault\" = true");

                    b.ToTable("DashboardBookmarks", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.DiscountApproval", b =>
                {
                    b.Property<Guid>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ApprovalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovalLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ApproverUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("CurrentDiscountPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("EscalatedToAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RejectionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("RequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Threshold")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("ApprovalId");

                    b.HasIndex("CurrentDiscountPercentage");

                    b.HasIndex("QuotationId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("ApproverUserId", "Status")
                        .HasFilter("\"ApproverUserId\" IS NOT NULL");

                    b.HasIndex("CreatedAt", "Status");

                    b.ToTable("DiscountApprovals", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.EmailNotificationLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMsg")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("LastRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("SENT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("LogId");

                    b.HasIndex("EventType");

                    b.HasIndex("NotificationId");

                    b.HasIndex("RecipientEmail");

                    b.HasIndex("SentAt")
                        .IsDescending();

                    b.HasIndex("Status")
                        .HasFilter("\"Status\" IN ('FAILED', 'BOUNCED')");

                    b.ToTable("EmailNotificationLog", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerificationTokens", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.ExportedReport", b =>
                {
                    b.Property<Guid>("ExportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExportFormat")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("FileSize")
                        .HasColumnType("integer");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ExportId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_ExportedReports_CreatedAt");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_ExportedReports_CreatedByUserId");

                    b.ToTable("ExportedReports", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExportedReports_ExportFormat", "\"ExportFormat\" IN ('pdf', 'excel', 'csv')");
                        });
                });

            modelBuilder.Entity("CRM.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DeliveredChannels")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("SENT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Meta")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RelatedEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelatedEntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("NotificationId");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("DeliveryStatus");

                    b.HasIndex("IsArchived");

                    b.HasIndex("IsRead");

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("RecipientUserId", "IsRead")
                        .HasFilter("\"IsRead\" = false");

                    b.HasIndex("RelatedEntityType", "RelatedEntityId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.NotificationPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PreferenceData")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId");

                    b.ToTable("NotificationPreferences", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_PasswordResetToken_ExpiresAt");

                    b.HasIndex("UserId", "UsedAt")
                        .HasDatabaseName("IX_PasswordResetToken_User_Active");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("INR");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<bool>("IsRefundable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentGateway")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PaymentReference")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("RefundDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefundReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("PaymentId");

                    b.HasIndex("PaymentDate");

                    b.HasIndex("PaymentReference")
                        .IsUnique();

                    b.HasIndex("PaymentStatus");

                    b.HasIndex("QuotationId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.PaymentGatewayConfig", b =>
                {
                    b.Property<Guid>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApiSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("GatewayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsTestMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("WebhookSecret")
                        .HasColumnType("text");

                    b.HasKey("ConfigId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Enabled");

                    b.HasIndex("GatewayName");

                    b.HasIndex("CompanyId", "GatewayName")
                        .IsUnique();

                    b.ToTable("PaymentGatewayConfigs", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.Quotation", b =>
                {
                    b.Property<Guid>("QuotationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CgstAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("DiscountPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("IgstAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<bool>("IsPendingApproval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("PendingApprovalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("QuotationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QuotationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("SgstAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("SubTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TaxAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("QuotationId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IsPendingApproval");

                    b.HasIndex("PendingApprovalId")
                        .IsUnique()
                        .HasFilter("\"PendingApprovalId\" IS NOT NULL");

                    b.HasIndex("QuotationDate");

                    b.HasIndex("QuotationNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("ValidUntil");

                    b.HasIndex("ClientId", "Status");

                    b.HasIndex("CreatedByUserId", "Status", "CreatedAt");

                    b.ToTable("Quotations", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.QuotationAccessLink", b =>
                {
                    b.Property<Guid>("AccessLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ClientEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FirstViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("LastViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("AccessLinkId");

                    b.HasIndex("AccessToken")
                        .IsUnique()
                        .HasDatabaseName("IX_QuotationAccessLinks_AccessToken");

                    b.HasIndex("ClientEmail")
                        .HasDatabaseName("IX_QuotationAccessLinks_ClientEmail");

                    b.HasIndex("QuotationId")
                        .HasDatabaseName("IX_QuotationAccessLinks_QuotationId");

                    b.HasIndex("QuotationId", "IsActive")
                        .HasDatabaseName("IX_QuotationAccessLinks_QuotationId_IsActive");

                    b.ToTable("QuotationAccessLinks", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.QuotationLineItem", b =>
                {
                    b.Property<Guid>("LineItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uuid");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitRate")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LineItemId");

                    b.HasIndex("QuotationId");

                    b.HasIndex("QuotationId", "SequenceNumber");

                    b.ToTable("QuotationLineItems", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.QuotationResponse", b =>
                {
                    b.Property<Guid>("ResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ClientName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("NotifiedAdminAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ResponseDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ResponseMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ResponseType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("ResponseId");

                    b.HasIndex("ClientEmail")
                        .HasDatabaseName("IX_QuotationResponses_ClientEmail");

                    b.HasIndex("QuotationId")
                        .IsUnique()
                        .HasDatabaseName("IX_QuotationResponses_QuotationId");

                    b.HasIndex("ResponseType")
                        .HasDatabaseName("IX_QuotationResponses_ResponseType");

                    b.ToTable("QuotationResponses", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.QuotationStatusHistory", b =>
                {
                    b.Property<Guid>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("HistoryId");

                    b.HasIndex("ChangedByUserId")
                        .HasDatabaseName("IX_QuotationStatusHistory_ChangedByUserId");

                    b.HasIndex("QuotationId")
                        .HasDatabaseName("IX_QuotationStatusHistory_QuotationId");

                    b.HasIndex("QuotationId", "ChangedAt")
                        .HasDatabaseName("IX_QuotationStatusHistory_QuotationId_ChangedAt");

                    b.ToTable("QuotationStatusHistory", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.QuotationTemplate", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("DiscountDefault")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("OwnerRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("SalesRep");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PreviousVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TemplateId");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("Name")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("PreviousVersionId")
                        .HasFilter("[PreviousVersionId] IS NOT NULL");

                    b.HasIndex("UpdatedAt")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.HasIndex("IsApproved", "Visibility")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.HasIndex("Name", "OwnerUserId")
                        .IsUnique()
                        .HasFilter("[DeletedAt] IS NULL");

                    b.HasIndex("OwnerUserId", "Visibility")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("QuotationTemplates", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.QuotationTemplateLineItem", b =>
                {
                    b.Property<Guid>("LineItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitRate")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("LineItemId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("TemplateId", "SequenceNumber");

                    b.ToTable("QuotationTemplateLineItems", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenJti")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("IsRevoked");

                    b.HasIndex("TokenJti")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.Refund", b =>
                {
                    b.Property<Guid>("RefundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ApprovalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovalLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("PaymentGatewayReference")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("RefundReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RefundReasonCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefundStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReversedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReversedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("RefundId");

                    b.HasIndex("ApprovedByUserId")
                        .HasDatabaseName("IX_Refunds_ApprovedByUserId");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("IX_Refunds_PaymentId");

                    b.HasIndex("QuotationId")
                        .HasDatabaseName("IX_Refunds_QuotationId");

                    b.HasIndex("RefundStatus")
                        .HasDatabaseName("IX_Refunds_Status");

                    b.HasIndex("RequestDate")
                        .HasDatabaseName("IX_Refunds_RequestDate");

                    b.HasIndex("RequestedByUserId")
                        .HasDatabaseName("IX_Refunds_RequestedByUserId");

                    b.ToTable("Refunds", null, t =>
                        {
                            t.HasCheckConstraint("CK_Refunds_Amount", "\"RefundAmount\" > 0");

                            t.HasCheckConstraint("CK_Refunds_ReasonCode", "\"RefundReasonCode\" IN ('CLIENT_REQUEST', 'ERROR', 'DISCOUNT_ADJUSTMENT', 'CANCELLATION', 'DUPLICATE_PAYMENT', 'OTHER')");

                            t.HasCheckConstraint("CK_Refunds_Status", "\"RefundStatus\" IN ('Pending', 'Approved', 'Processing', 'Completed', 'Failed', 'Reversed')");
                        });
                });

            modelBuilder.Entity("CRM.Domain.Entities.RefundTimeline", b =>
                {
                    b.Property<Guid>("TimelineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EventDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("RefundId")
                        .HasColumnType("uuid");

                    b.HasKey("TimelineId");

                    b.HasIndex("ActedByUserId")
                        .HasDatabaseName("IX_RefundTimeline_ActedByUserId");

                    b.HasIndex("EventDate")
                        .HasDatabaseName("IX_RefundTimeline_EventDate");

                    b.HasIndex("RefundId")
                        .HasDatabaseName("IX_RefundTimeline_RefundId");

                    b.ToTable("RefundTimeline", null, t =>
                        {
                            t.HasCheckConstraint("CK_RefundTimeline_EventType", "\"EventType\" IN ('REQUESTED', 'APPROVED', 'REJECTED', 'PROCESSING', 'COMPLETED', 'FAILED', 'REVERSED')");
                        });
                });

            modelBuilder.Entity("CRM.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("RoleId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Roles_IsActive");

                    b.HasIndex("RoleName")
                        .IsUnique()
                        .HasDatabaseName("UX_Roles_RoleName");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.SavedSearch", b =>
                {
                    b.Property<Guid>("SavedSearchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilterCriteria")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("SearchName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SortBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SavedSearchId");

                    b.ToTable("SavedSearches");
                });

            modelBuilder.Entity("CRM.Domain.Entities.ScheduledReport", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmailRecipients")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("LastSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NextScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecurrencePattern")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<JsonDocument>("ReportConfig")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("ReportId");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_ScheduledReports_CreatedByUserId");

                    b.HasIndex("IsActive", "NextScheduledAt")
                        .HasDatabaseName("IX_ScheduledReports_IsActive_NextScheduledAt");

                    b.ToTable("ScheduledReports", null, t =>
                        {
                            t.HasCheckConstraint("CK_ScheduledReports_RecurrencePattern", "\"RecurrencePattern\" IN ('daily', 'weekly', 'monthly')");
                        });
                });

            modelBuilder.Entity("CRM.Domain.Entities.SuspiciousActivityFlag", b =>
                {
                    b.Property<Guid>("FlagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HistoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<List<string>>("Reasons")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid");

                    b.Property<short>("Score")
                        .HasColumnType("smallint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("OPEN");

                    b.HasKey("FlagId");

                    b.HasIndex("HistoryId");

                    b.HasIndex("ClientId", "DetectedAt")
                        .HasDatabaseName("IX_SuspiciousActivityFlags_Client_DetectedAt");

                    b.HasIndex("Status", "DetectedAt")
                        .HasDatabaseName("IX_SuspiciousActivityFlags_Status_DetectedAt");

                    b.ToTable("SuspiciousActivityFlags", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("citext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("LoginAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<Guid?>("ReportingManagerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("ReportingManagerId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_UserRoles_RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Entities.Adjustment", b =>
                {
                    b.HasOne("CRM.Domain.Entities.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM.Domain.Entities.Quotation", "Quotation")
                        .WithMany()
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Quotation");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("CRM.Domain.Entities.AnalyticsMetricsSnapshot", b =>
                {
                    b.HasOne("CRM.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Client", b =>
                {
                    b.HasOne("CRM.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("CRM.Domain.Entities.ClientHistory", b =>
                {
                    b.HasOne("CRM.Domain.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActorUser");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("CRM.Domain.Entities.DashboardBookmark", b =>
                {
                    b.HasOne("CRM.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CRM.Domain.Entities.DiscountApproval", b =>
                {
                    b.HasOne("CRM.Domain.Entities.User", "ApproverUser")
                        .WithMany()
                        .HasForeignKey("ApproverUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM.Domain.Entities.Quotation", "Quotation")
                        .WithMany()
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApproverUser");

                    b.Navigation("Quotation");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("CRM.Domain.Entities.EmailNotificationLog", b =>
                {
                    b.HasOne("CRM.Domain.Entities.Notification", "Notification")
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("CRM.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("CRM.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CRM.Domain.Entities.ExportedReport", b =>
                {
                    b.HasOne("CRM.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Notification", b =>
                {
                    b.HasOne("CRM.Domain.Entities.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("CRM.Domain.Entities.NotificationPreference", b =>
                {
                    b.HasOne("CRM.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("CRM.Domain.Entities.NotificationPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CRM.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("CRM.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Payment", b =>
                {
                    b.HasOne("CRM.Domain.Entities.Quotation", "Quotation")
                        .WithMany()
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("CRM.Domain.Entities.PaymentGatewayConfig", b =>
                {
                    b.HasOne("CRM.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Quotation", b =>
                {
                    b.HasOne("CRM.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.DiscountApproval", "PendingApproval")
                        .WithOne()
                        .HasForeignKey("CRM.Domain.Entities.Quotation", "PendingApprovalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("CreatedByUser");

                    b.Navigation("PendingApproval");
                });

            modelBuilder.Entity("CRM.Domain.Entities.QuotationAccessLink", b =>
                {
                    b.HasOne("CRM.Domain.Entities.Quotation", "Quotation")
                        .WithMany()
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("CRM.Domain.Entities.QuotationLineItem", b =>
                {
                    b.HasOne("CRM.Domain.Entities.Quotation", "Quotation")
                        .WithMany("LineItems")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("CRM.Domain.Entities.QuotationResponse", b =>
                {
                    b.HasOne("CRM.Domain.Entities.Quotation", "Quotation")
                        .WithMany()
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("CRM.Domain.Entities.QuotationStatusHistory", b =>
                {
                    b.HasOne("CRM.Domain.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CRM.Domain.Entities.Quotation", "Quotation")
                        .WithMany()
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("CRM.Domain.Entities.QuotationTemplate", b =>
                {
                    b.HasOne("CRM.Domain.Entities.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM.Domain.Entities.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.QuotationTemplate", "PreviousVersion")
                        .WithMany()
                        .HasForeignKey("PreviousVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApprovedByUser");

                    b.Navigation("OwnerUser");

                    b.Navigation("PreviousVersion");
                });

            modelBuilder.Entity("CRM.Domain.Entities.QuotationTemplateLineItem", b =>
                {
                    b.HasOne("CRM.Domain.Entities.QuotationTemplate", "Template")
                        .WithMany("LineItems")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("CRM.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("CRM.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Refund", b =>
                {
                    b.HasOne("CRM.Domain.Entities.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM.Domain.Entities.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.Quotation", "Quotation")
                        .WithMany()
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Payment");

                    b.Navigation("Quotation");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("CRM.Domain.Entities.RefundTimeline", b =>
                {
                    b.HasOne("CRM.Domain.Entities.User", "ActedByUser")
                        .WithMany()
                        .HasForeignKey("ActedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.Refund", "Refund")
                        .WithMany("Timeline")
                        .HasForeignKey("RefundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActedByUser");

                    b.Navigation("Refund");
                });

            modelBuilder.Entity("CRM.Domain.Entities.ScheduledReport", b =>
                {
                    b.HasOne("CRM.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("CRM.Domain.Entities.SuspiciousActivityFlag", b =>
                {
                    b.HasOne("CRM.Domain.Entities.ClientHistory", "History")
                        .WithMany("Flags")
                        .HasForeignKey("HistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("History");
                });

            modelBuilder.Entity("CRM.Domain.Entities.User", b =>
                {
                    b.HasOne("CRM.Domain.Entities.User", "ReportingManager")
                        .WithMany("DirectReports")
                        .HasForeignKey("ReportingManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReportingManager");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CRM.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("CRM.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CRM.Domain.Entities.ClientHistory", b =>
                {
                    b.Navigation("Flags");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Quotation", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("CRM.Domain.Entities.QuotationTemplate", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Refund", b =>
                {
                    b.Navigation("Timeline");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CRM.Domain.Entities.User", b =>
                {
                    b.Navigation("DirectReports");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
